CREATE DATABASE TRANSLEO
GO 
USE TRANSLEO
GO

CREATE TABLE TL_CLIENTES(
NOMBRE NVARCHAR(20) NOT NULL,
APELLIDOS NVARCHAR(40) NOT NULL,
CODIGO INT NOT NULL CONSTRAINT PK_CODIGOCLIENTE PRIMARY KEY,
DIRECCION NVARCHAR(80) NOT NULL,
CIUDAD NVARCHAR(20) NOT NULL,
CP INT NOT NULL CONSTRAINT CP_TL_CIENTE CHECK (CP LIKE '[][][][][]'),
PROVINCIA NVARCHAR(20),
TELEFONO NCHAR(9) CONSTRAINT SOLONUMEROS_TELEFONOCLIENT CHECK(TELEFONO IN(1,2,3,4,5,6,7,8,9,0)),
TELEFONO_ALT NCHAR(9) CONSTRAINT SOLONUMEROS_TELEFONOALT_CLIENT CHECK(TELEFONO_ALT IN(1,2,3,4,5,6,7,8,9,0)), 
USUARIO NVARCHAR (15) NOT NULL,
CONTRASEÑA NVARCHAR (10) NOT NULL,
)


CREATE TABLE  TL_PAQUETES(
CODIGO BIGINT NOT NULL CONSTRAINT PK_CODIGO_PAQUETE PRIMARY KEY,
ALTO INT NOT NULL,
LARGO INT NOT NULL,
ANCHO INT NOT NULL,
PESO INT NOT NULL,
CODCLIENTEENVIO INT NOT NULL CONSTRAINT FK_CODCLIENTE_ENVIO FOREIGN KEY REFERENCES TL_CLIENTES(CODIGO),
CODCLIENTEREMITENTE INT NOT NULL CONSTRAINT FK_CODCLIENTE_REMITENTE FOREIGN KEY REFERENCES TL_CLIENTES(CODIGO)
)

CREATE TABLE TL_CENTROS(
CODIGO INT NOT NULL CONSTRAINT PK_COD_CENTROS PRIMARY KEY,
DENOMINACION NVARCHAR (40),
DIRECCION NVARCHAR (80) NOT NULL,
CIUDAD NVARCHAR(20) NOT NULL,
CP INT NOT NULL CONSTRAINT CP_TL_CENTROS CHECK (CP LIKE '[][][][][]'),
PROVINCIA NVARCHAR (20),
TELEFONO NCHAR (9) CONSTRAINT SOLONUMEROS_TLFCENTRO CHECK( TELEFONO IN (1,2,3,4,5,6,7,8,9,0)),
TELEFONO_ALT NCHAR (9) CONSTRAINT SOLONUMEROS_TLF_ALT_CENTRO CHECK(TELEFONO_ALT IN (1,2,3,4,5,6,7,8,9,0))
)

CREATE TABLE VEHICULOS (
MATRICULA NCHAR (7) NOT NULL CONSTRAINT PK_MATRICULA_VEHICULOS PRIMARY KEY,
TIPO NCHAR(1) CONSTRAINT TIPO_VEHICULO_CARACTER CHECK (TIPO LIKE '[abcdefghijklmnñopqrstuvwz]'),
)